name: Release

on:
  release:
    types: 
      - published

permissions: {}

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v5.0.0
        
      - name: Update manifest.json version to ${{ github.event.release.tag_name }}
        shell: bash
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/isitpayday/manifest.json"

      - name: ZIP the integration directory
        shell: bash
        run: |
          cd "${{ github.workspace }}/custom_components/isitpayday"
          zip isitpayday.zip -r ./

      - name: Upload the ZIP file to the release
        uses: softprops/action-gh-release@v2.3.3
        with:
          files: ${{ github.workspace }}/custom_components/isitpayday/isitpayday.zip
