name: Sync labels

on:
  push:
    branches:
      - main
    paths:
      - .github/sync-labels.yml
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v5.0.0

      - name: 🚀 Run Label Syncer
        uses: brpaz/action-label-syncer@0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/sync-labels.yml
